### ISSUE TITLE
Scripting the implementation of BTrace addon in Blender

### ISSUE THREAD

**Issue by rahul1947** [sobotka/blender-addons#1]
Hello @julienduroure and the team.

I'm trying to automate the process done by BTrace add-on. And I had some issues in the implementation. 

Could you please look into [this](https://blender.stackexchange.com/questions/136103/scripting-the-generation-of-a-curve-from-the-set-of-mesh-centers-drawn-using-btr)?

**Comment by sobotka** [comment]
This is a mirror. Use the official tracker.
